// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
#nullable enable
using System;

namespace SFLib.Interop;

[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
public sealed class LuaAttribute : Attribute
{
    /// <summary>
    /// The name of the Lua function or variable. If not specified, the C# member name is used.
    /// </summary>
    public string? Name;
    /// <summary>
    /// If set, indicates that this member corresponds to a static method in Lua. The value is the name of the Lua function.
    /// </summary>
    public string? StaticMethod;
    /// <summary>
    /// If set, indicates that this member corresponds to an instance method in Lua. The value is the name of the Lua function.
    /// </summary>
    public string? Method;
    /// <summary>
    /// If set, indicates that this member corresponds to a Lua module. The value is the name of the Lua module.
    /// </summary>
    public string? Module;
    /// <summary>
    /// If set, indicates that this member corresponds to a Lua class. The value is the name of the Lua class.
    /// When lowering, this type will become `local cls = class("{Class}")`.
    /// </summary>
    public string? Class;
    /// <summary>
    /// If set, indicates that this class requires a Lua module. Affects code sorting and ensures the module is loaded before the class is defined. The value is the name of the Lua module.
    /// </summary>
    public string? Require;
    /// <summary>
    /// If true, indicates that this class should be treated as a Lua table literal. When lowering, this type will become `local tbl = { ... }` instead of `local cls = class("...")`.
    /// </summary>
    public bool TableLiteral;

    public LuaAttribute()
    {
    }
}

public class LuaObject
{
    public LuaObject()
    {
    }
}

public static class LuaInterop
{
    public static LuaObject CreateTable() => default!;

    public static LuaObject Require(string moduleName) => default!;

    public static T Require<T>(string moduleName) => default!;

    public static T Get<T>(LuaObject target, object key) => default!;

    public static T GetGlobal<T>(string name) => default!;

    public static void Set(LuaObject target, object key, object? value)
    {
    }

    public static void SetGlobal(string name, object? value)
    {
    }

    public static void Call(LuaObject target, string functionName, params object?[] arguments)
    {
    }

    public static T Call<T>(LuaObject target, string functionName, params object?[] arguments) => default!;

    public static void CallMethod(LuaObject target, string methodName, params object?[] arguments)
    {
    }

    public static T CallMethod<T>(LuaObject target, string methodName, params object?[] arguments) => default!;

    public static void CallGlobal(string functionName, params object?[] arguments)
    {
    }

    public static T CallGlobal<T>(string functionName, params object?[] arguments) => default!;
}